### ISSUE TITLE
block syntax still exists

### ISSUE THREAD

**Issue by joyously** [wp-cms/wp-cms#21]
https://github.com/wp-cms/wp-cms/blob/7aadd93f85243537518e888344abccad74bd249c/src/wp-admin/includes/upgrade.php#L194-L212

https://github.com/wp-cms/wp-cms/blob/7aadd93f85243537518e888344abccad74bd249c/src/wp-admin/post.php#L100-L102

https://github.com/wp-cms/wp-cms/blob/7aadd93f85243537518e888344abccad74bd249c/src/wp-admin/includes/class-wp-privacy-policy-content.php#L642-L646

https://github.com/wp-cms/wp-cms/blob/main/src/wp-includes/class-wp-block-parser.php

https://github.com/wp-cms/wp-cms/blob/7aadd93f85243537518e888344abccad74bd249c/src/wp-includes/theme.php#L2364

https://github.com/wp-cms/wp-cms/blob/7aadd93f85243537518e888344abccad74bd249c/src/wp-includes/theme.php#L2372

https://github.com/wp-cms/wp-cms/blob/7aadd93f85243537518e888344abccad74bd249c/src/wp-includes/theme.php#L2380

https://github.com/wp-cms/wp-cms/blob/7aadd93f85243537518e888344abccad74bd249c/src/wp-includes/theme.php#L2397

**Comment by wp-cms** [comment]
Thanks for pointing those out @joyously - True, there is still some blocks related code in the codebase which I haven't yet identified. I'm still chasing those down and removing them.

**Comment by wp-cms** [comment]
I removed some of it: https://github.com/wp-cms/wp-cms/pull/24/files

Will keep working on that, there are other places with blocks related code, but I need to go step by step and test the build process and php unit tests, thanks for helping.

**Comment by adegans** [comment]
Not sure if the above code is related, but it makes sense to keep some support for blocks to accommodate people switching from it to no blocks. And some plugins may just require it even though it is optional as well.

something to consider…

**Comment by wp-cms** [comment]
@adegans "some support" doesn't make sense. One function depends on the other and the other on another. If people need blocks, they should use WordPress, which covers them.

Plugins that require blocks to function are not supposed to work on WP CMS.
