### ISSUE TITLE
releases

### ISSUE THREAD

**Issue by joyously** [wp-cms/wp-cms#22]
This repository doesn't point to a release.
The wp-cms.dev download page has a simple link to a zip, but no hash to confirm.
The zip that is there contains all of the bundled themes instead of just the last 3 or 4 (no WP release has all of them), so it seems that something is amiss in the release process.

**Comment by wp-cms** [comment]
Thanks @joyously - Yes, the release process isn't yet working the way it should. I'll make this a priority and inform once ready.

**Comment by adegans** [comment]
So what’s the best place to get a release and ultimately updates? Any guidance?
I should probably get it from your site? Since there is no release here?

**Comment by wp-cms** [comment]
Yes @adegans , it's available on the website.

**Now on GitHub too**: https://github.com/wp-cms/wp-cms/releases/download/6.1/wp-cms-6.1.zip
