### ISSUE TITLE
Can I check if WP-CMS or WordPress is installed

### ISSUE THREAD

**Issue by tmconnect** [wp-cms/wp-cms#28]
In my theme I want to check if WP-CMS or WordPress is running.

Is there any function to check this?

Thanks, Thomas

**Comment by joyously** [comment]
Just like browser sniffing, it's not a good idea. 
You should use functionality checks like `if function_exists( 'some_block_function')` for the function you want.

**Comment by wp-cms** [comment]
Yes, @joyously answered that question with a valid point.
